### PR TITLE
Fixed bc issues

### PR DESCRIPTION
**Pull request by cleentfaar**
Certain services need to be public to make the magic injections work in symfony 4 (public defaults to false since 4). Obviously this is only done as we expect this package to become EOL (instead of making the injections work without this).

### CODE REVIEW

**Comment by cleentfaar** [comment]
No idea why tests are failing now on php5 (?) packages, and not in earlier PRs. Did someone re-enable CI?

**Comment by rgeraads** [comment]
> No idea why tests are failing now on php5 (?) packages, and not in earlier PRs. Did someone re-enable CI?

This is probably because composer 2.0 is now being used, which performs some additional checks. Maybe we can force v1?

**Review by rgeraads — APPROVED** [review]

**Comment by pkruithof** [comment]
> Certain services need to be public to make the magic injections work in symfony 4

Services don't need to be public for DI to work. I'm not sure what the issue is here, but I think it's a different problem.

I'm fine with making these services public though. Like you said, this package is kinda EOL anyway.

**Comment by pkruithof** [comment]
> No idea why tests are failing now on php5 (?) packages, and not in earlier PRs. Did someone re-enable CI?

It seems to be failing on this part: https://github.com/treehouselabs/queue-bundle/blob/master/tests/travis/install.sh#L6-L13
I think we have to check if installing the amqp extension is different for the PHP version that Travis is using atm.

**Pull request merged**
